"""empty message

Revision ID: 4691a574d8ba
Revises: 0cb2e0e01bb3
Create Date: 2025-02-14 15:02:26.687435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4691a574d8ba'
down_revision: Union[str, None] = '0cb2e0e01bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ERROR', 'GOOD', name='sensorstatustype'), nullable=False),
    sa.Column('id_sensor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sensor'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
