version: '3'
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - 9094:9094
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_MESSAGE_MAX_BYTES: 20971520

      # KAFKA_ADVERTISED_HOST_NAME: localhost

      # создание очередей
      KAFKA_CREATE_TOPICS: "requests:1:1,responses:1:1"
    depends_on:
      - zookeeper

  rabbit:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672

  admin:

    image: quay.io/cloudhut/kowl:master
    links:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    ports:
      - 8080:8080

    depends_on:
      - zookeeper
      - kafka
